### ISSUE TITLE
Generate contract and state json from the terminal

### ISSUE THREAD

**Issue by kugiyasan** [input-output-hk/marlowe-cardano#157]
## Describe the feature you'd like

I wrote my own smart contract and I want to use it on the public testnet, however it seems like marlowe-cli can only generate tx.contract and tx.state from the `marlowe-cli template` command.
A new command like `marlowe-cli compile` would solve my issue. This new command will parse a marlowe contract from a file and then call [`makeExample`](https://github.com/input-output-hk/marlowe-cardano/blob/700c0f59ac1cf2ef153e690ff0bbaa799eac3d8f/marlowe-cli/src/Language/Marlowe/CLI/Examples.hs#L31).

**Comment by kugiyasan** [comment]
Yes actually, I realized a few days after opening this issue that the marlowe playground did offer the feature I wanted with the "Download as JSON" button... I guess I was simply surprised by the fact that the cli is missing a lot of features from the playground, I assumed that both interfaces would share a lot of code behind the scene...

**Comment by hrajchert** [comment]
If we want to be able to parse the textual representation of Marlowe (not the JSON AST) we need to investigate of a good way to define the BNF grammar and share it between the projects. I've created [issue 165](https://github.com/input-output-hk/marlowe-cardano/issues/165) to capture this work.

**Comment by nhenin** [comment]
For now we want to stick to json format on the CLI layer and we are planning to provide proper syntax for Marlowe in the future.
