### ISSUE TITLE
Report warnings during `auto` contract execution

### ISSUE THREAD

**Issue by edsko** [input-output-hk/marlowe-cardano#174]
The `auto` endpoint provides "automatic" contract execution for Marlow contracts that are amenable to this. A key function in this process is

```haskell
getAction :: MarloweTimeRange -> Party -> MarloweData -> PartyAction
```

which computes what action should happen next. Like regular contract execution, this depends on `reduceContractUntilQuiescent`, but unlike regular execution, it [silently swallows any `ReduceWarning`s](https://github.com/input-output-hk/marlowe-cardano/blob/294c0a06e961ed83887e63a8ad135fcb1425c179/marlowe/src/Language/Marlowe/Client.hs#L966) . This can be pretty confusing, because the perspective of the Marlow contract author, those "warnings" can be pretty serious; for example, if the contract stipulates that a payment should happen but there are insufficient funds, the payment is simply skipped. The execution log in this case will merely record the next action in the transaction, with zero indication that anything was skipped.

Perhaps it would make sense to bubble up these warnings from `getAction` and then log them as warnings (or even errors) in `autoExecuteContract` (in `marlowePlutusContract`)? (Happy to submit a PR.)

**Comment by bwbush** [comment]
@edsko, thank you for pointing this out. I agree that it is important for the warnings to be reported. We'd be happy to review a PR if you'd like to submit one; if not, we will queue this for the Marlowe team to address.

**Comment by edsko** [comment]
Thanks @bwbush . I have opened #181; it's only small.

**Comment by bwbush** [comment]
The PR request for this was accepted.
