### ISSUE TITLE
Support for post-Vasil `plutus-apps` libraries

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [input-output-hk/marlowe-cardano#186]
## Describe the feature you'd like

The `next-node` branch in `input-output-hk/plutus-apps` is tracking the changes required for compatibility with `cardano-node >= 1.35`. It would be nice if this repository had a similar `next-node` branch that depended on the `next-node` branch of `plutus-apps`. I couldn't find if there was a branch containing these changes already. As far as I can tell, the changes from that version of `plutus-apps` will need to be integrated for compatibility with the public testnet and for mainnet after the Vasil HF.

## Describe alternatives you've considered

I've tried to update the pinned `plutus-apps` version in this repository to the `next-node` branch myself. The first issue is that [an `aeson >= 2.0` constraint is introduced](https://github.com/input-output-hk/plutus-apps/blob/next-node/cabal.project#L41), which causes build errors due to the `ToJSON` instance for `Input` using `HashMap` as the object type. After fixing that by replacing `HashMap` usage with `KeyMap` from `aeson`, there are some more difficult-to-fix failures due to the changes introduced by https://github.com/input-output-hk/plutus-apps/pull/526.

I understand if this sort of support is not something the Marlowe team has the capacity for, so feel free to close if that's the case. Any information regarding compatibility with post-Vasil Plutus libraries would be appreciated!

**Comment by bwbush** [comment]
The current `main` of Marlowe is actually using a long-lived fork of `plutus-apps`, so updating to the tip of `plutus-apps` would involve cherry-picking in addition to updating dependencies.

**Comment by paluh** [comment]
Hi @FinleyMcIlwaine,

I created this [SCP-4235](https://github.com/input-output-hk/marlowe-cardano/tree/SCP-4235) branch on which we want to progress the development of the core Marlowe pieces against new node release. I'm going to finish up the code and nix cleanup up this week because we want to start experimenting with reference scripts etc.
Unfortunately we don't have plans to update our plutus apps dependent pieces at the moment.

**Comment by nhenin** [comment]
not relevant anymore since we removed our dependencies with the `plutus-apps` repository.
