### ISSUE TITLE
Decoupling ACTUS core from ACTUS Marlowe

### ISSUE THREAD

**Issue by morganthomas** [input-output-hk/marlowe-cardano#441]
## Describe the feature you'd like

I'd like to be able to depend on the `actus-core` modules without pulling in the Cardano universe. Towards that, I'd like them to be in their own package with a minimal dependency footprint.

## Describe alternatives you've considered

I have copy-pasted those modules into my project, with an appropriate copyright notice. The downside of this approach is added friction in downstreaming or upstreaming changes.

## Additional context / screenshots

I am willing to do the work. I would be more motivated to do it if I knew that the project maintainers would in principle accept such a change.

**Comment by yveshauser** [comment]
Thanks for suggesting this. We support the decoupling of `actus-core` into a proper module to allow collaborations for further development / improvements of the code.

**Comment by yveshauser** [comment]
You can find the `actus-core` module at: https://github.com/input-output-hk/actus-core
