### ISSUE TITLE
--submit: cannot parse value `600'

### ISSUE THREAD

**Issue by rhystmorgan** [input-output-hk/marlowe-cardano#570]
## Summary

I am having trouble submitting transactions through marlowe-cli using

`marlowe-cli run auto-execute`

I am getting an error like this:

>   --submit 600
option --submit: cannot parse value `600'

>   --submit=600
option --submit: cannot parse value `600'

I am going through the zcb marlowe-cli example from youtube, which is why I tried a space before '='

## Steps to reproduce

1. latest version of marlowe-cli (installed today)
2. following the video, init a zcb contract with params
3. marlowe-cli run auto-execute ... the initial deposit

## Expected behavior

Expected behavior is tx submitted to the blockchain, actual  behavior: error.

I have also tried just signing the tx and submitting it through cardano-cli, but there is a separate error with that regarding the serialization format and ledger CDDL format

## System info (please complete the following information):

- OS: Ubuntu
- Version 20.04
- cloned marlowe-cardano.git as per the README.md

## Screenshots and attachments

Output in terminal:

marlowe-cli run auto-execute \
>   --marlowe-out-file marlowe-1.json \
>   --change-address addr_testxxxxxxxxxx \
>   --required-signer xxxxxxxxxx.skey \
>   --out-file tx1.signed \
>   --submit=600
option --submit: cannot parse value `600'

Usage: marlowe-cli run auto-execute ...

I also get the same issue with --submit 600

## Additional context

I hope I am just missing something silly and there is something simple I can do to get it right

**Comment by paluh** [comment]
Thanks a lot for the detailed report. A quick workaround is to add `s` (like `--submit=600s`) to the value. A proper fix is on the way ;-)

**Comment by bwbush** [comment]
Same as https://input-output.atlassian.net/browse/PLT-5844.

**Comment by paluh** [comment]
Fixed: https://github.com/input-output-hk/marlowe-cardano/pull/576
