### ISSUE TITLE
Marlowe Run - Templates not running

### ISSUE THREAD

**Issue by FrankC01** [input-output-hk/marlowe-cardano#7]
## Summary

Running sample templates in Marlowe Run do not appear to start

## Steps to reproduce

1. Clone and build as per README
2. start marlowe pab and do npm run start
3. In browser create and connect two (2) wallets
4. From first wallet select Load template, setup and begin
5. In the first wallet, it just spins on 'Starting....'
6. In second wallet no change after connecting the wallet

This is on the marlow-pad screen after step 4
```base
[pab:Info:248] [2021-10-30 10:52:07.00 UTC] Finished balancing. 12a1efa64a3b6f357c1dfcd060f0a320d05894895f311a37b73dda6eb4b1c5a9
[pab:Info:248] [2021-10-30 10:52:07.07 UTC] Submitting tx: 12a1efa64a3b6f357c1dfcd060f0a320d05894895f311a37b73dda6eb4b1c5a9
[pab:Info:12] [2021-10-30 10:52:08.00 UTC] Processing chain event  TxnValidate 12a1efa64a3b6f357c1dfcd060f0a320d05894895f311a37b73dda6eb4b1c5a9
[pab:Info:274] [2021-10-30 10:52:08.43 UTC] Initialising contract MarloweFollower with ID 78ddc1b1-4d19-46a0-8987-fad8faca780b
[pab:Info:274] [2021-10-30 10:52:08.71 UTC] Activated instance 78ddc1b1-4d19-46a0-8987-fad8faca780b on Wccc572a
```
And then nothing

## Expected behavior

I expected that the contract would start and I would have visible feedback in Wallet 1
I expected that Wallet 2 would be presented with the loan request
I expected I could run the demo to completion

## System info (please complete the following information):

- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- marlowe-cardano cloned 10/26/2021 @ 3:00 PM EDT

**Comment by nhenin** [comment]
Doesn't exist anymore...
