### ISSUE TITLE
Marlowe Runtime REST API invalid

### ISSUE THREAD

**Issue by nicolasLuduena** [input-output-hk/marlowe-cardano#752]
## Summary

I am trying to generate code automatically from the OpenAPI spec however it's not possible without having to tinker with it manually. The current spec is not a valid OpenAPI spec.

## Steps to reproduce

1. Run Marlowe Runtime REST API with `cabal run marlowe-web-server -- --marlowe-runtime-host localhost -o -a`.
3. Go to `http://localhost:8080/openapi.json`.
4. Download the output of that url in a file named `openapi.json`.
5. Run `npx @openapitools/openapi-generator-cli validate -i openapi.json`.
This is the output:
```
Validating spec (openapi.json)
Errors:
  - attribute components.schemas.MarloweState.items is not of type object
  - attribute components.schemas.Plutus.StakingCredential.items is missing
  - attribute components.schemas.Plutus.StakingCredential.items is not of type object
  - attribute components.schemas.MarloweState.items is missing
Warnings: 
  - Unused model: WithdrawTxBodyEnvelope
  - Unused model: CreateTxBodyEnvelope

[error] Spec has 4 errors.
```

## Expected behavior
No errors here. Maybe a Github action that does this validation so the developers know if the latest commit has a valid OpenAPI spec.

## System info

- OS: Linux Mint 
- Version: 21 Cinnamon
- Plutus version or commit hash: 54c0074040adf5f2065b4f759b7883f45821053f

**Comment by bjornkihlberg** [comment]
Thanks for reporting this!

I'm currently working on applying these fixes in this ticket: https://github.com/input-output-hk/marlowe-ts-sdk/issues/100.

> Maybe a Github action that does this validation so the developers know if the latest commit has a valid OpenAPI spec.

This is a good suggestion and something we want to do to prevent issues in the future.

**Comment by nicolasLuduena** [comment]
Thanks Bjorn! Btw if you are going to use 'oneOf',  going for  a change like [this](https://gist.github.com/nicolasLuduena/5e1032ca7bb6a5ac1acdc72fb7c5ef8e) changes the generated code radically.

Here's an example:
```typescript
export type Contract = ContractOneOf | ContractOneOf1 | ContractOneOf2 | ContractOneOf3 | ContractOneOf4 | ContractOneOf5;
```
to this
```typescript
export type Contract = Assert | Close | If | Let | Pay | When;
```
The description for each schema is also transferred as comments & documentation!

**Comment by bjornkihlberg** [comment]
Hello again,

As I solved the issues earlier today, someone on my team noted that the schema satisfies OpenApi 3.1 so the old issue was dropped and [a new one](https://github.com/input-output-hk/marlowe-ts-sdk/issues/109) is created to solve this.

**Comment by bjornkihlberg** [comment]
We are now targeting OpenApi 3.1.0 in marlowe runtime on the `main` branch which means that heterogeneous arrays should be allowed for the `items` field in the schema. If there are any further issues, don't hesitate to notify us!

**Comment by paluh** [comment]
@nicolasLuduena can we close this issue?
